// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdBgNZkg6TjJ8IntLUDZxTFv9ZeEITTws',
    appId: '1:454897328455:web:30bf6da2da63a0fbf0ec62',
    messagingSenderId: '454897328455',
    projectId: 'wito-3a8da',
    authDomain: 'wito-3a8da.firebaseapp.com',
    storageBucket: 'wito-3a8da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpgtVLVupvw-BDlx9wKQhe6sRwS4HLTgY',
    appId: '1:454897328455:android:e37bc20f45259193f0ec62',
    messagingSenderId: '454897328455',
    projectId: 'wito-3a8da',
    storageBucket: 'wito-3a8da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhmL8DsEisZgIcRCzvgy_bX3S1lOByN5A',
    appId: '1:454897328455:ios:d67f9e3acee5da7bf0ec62',
    messagingSenderId: '454897328455',
    projectId: 'wito-3a8da',
    storageBucket: 'wito-3a8da.appspot.com',
    iosClientId: '454897328455-374ab50ghr4sra71foijg8jgac22ep5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.wito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhmL8DsEisZgIcRCzvgy_bX3S1lOByN5A',
    appId: '1:454897328455:ios:7bf548644052d251f0ec62',
    messagingSenderId: '454897328455',
    projectId: 'wito-3a8da',
    storageBucket: 'wito-3a8da.appspot.com',
    iosClientId: '454897328455-mjv2eattn5dmr1r8sa9mav9a3ft5o2bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.wito.RunnerTests',
  );
}
